import type { Metadata } from "next";
import { Merriweather, Geist_Mono } from "next/font/google";
import "./styles/main.css";
import "./globals.css";
import Navbar from "@/components/Header";
import Footer from "@/components/Footer";

const merriweatherSans = Merriweather({
  variable: "--font-merriweather-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Swastik Manpower" />
      </head>
      <body
        className={`${merriweatherSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
